
const _REQUESTS = {
	RESET: 0,
	// SET_MODEM_CTRL: 1,
	// SET_FLOW_CTRL: 2,
	// SET_BAUDRATE: 3,
	// SET_DATA: 4,
	POLL_MODEM_STATUS: 0x05,
	// SET_EVENT_CHAR: 0x06,
	// SET_ERROR_CHAR: 0x07,
	SET_LATENCY_TIMER: 0x09,
	GET_LATENCY_TIMER: 0x0A,
	SET_BITMODE: 0x0B,
	// READ_PINS: 0x0C,
	// READ_EEPROM: 0x90,
	// WRITE_EEPROM: 0x91,
	// ERASE_EEPROM: 0x92,
} as const

export type RequestKeys = keyof typeof _REQUESTS
export type RequestType = number
export const REQUESTS: Record<RequestKeys, RequestType> = _REQUESTS


export type BitMode = number

// specified in 16bit-little-endian
export const BIT_MODE: Record<string, BitMode> = {
  RESET: 0x00_00, // bitbang OFF / regular serial/FIFO
  // BITBANG: 0x01, // async bitbang (classic)
  MPSSE: 0x02_00, // MPSSE mode
  // SYNCBB: 0x04, // synchronous bitbang
  // MCU: 0x08, // MCU Host Bus Emulation
  // OPTO: 0x10, // Opto-Isolated Serial Interface Mode
  // CBUS: 0x20, // Bitbang on CBUS
  // SYNCFF: 0x40, // Single Channel Synchronous FIFO mode,
  // FT1284: 0x80, // FT1284
}

export const RESET_USB = {
	RESET: 0,
	RX: 1,
	TX: 2
}

// Shifting commands IN MPSSE Mode
export const SHIFT_COMMANDS_DEFINITION = {
	WRITE_NEGATIVE_EDGE: 0b0000_0001, // -ve CLK on write
	BIT_MODE:            0b0000_0010, // bit mode = 1 else byte mode
	READ_NEGATIVE_EDGE:  0b0000_0100, // -ve CLK on read
	LSB_FIRST:           0b0000_1000, // LSB first = 1 else MSB first
	WRITE_TDI:           0b0001_0000, // Do write TDI
	READ_TDO:            0b0010_0000, // Do read TDO
	WRITE_TMS:           0b0100_0000  // Do writeTMS
}

export const SHIFT_COMMAND = {
	OUT_MSB_BYTES_POSITIVE_VE: 0x10, // WRITE_TDI
	OUT_MSB_BYTES_NEGATIVE_VE: 0x11, // WRITE_TDI | WRITE_NEGATIVE_EDGE
	OUT_MSB_BITS_POSITIVE_VE:  0x12, // WRITE_TDI | BIT_MODE
	OUT_MSB_BITS_NEGATIVE_VE:  0x13, // WRITE_TDI | BIT_MODE | WRITE_NEGATIVE_EDGE

	IN_MSB_BYTES_POSITIVE_VE: 0x20, // READ_TDO
	IN_MSB_BYTES_NEGATIVE_VE: 0x24, // READ_TDO | READ_NEGATIVE_EDGE
	IN_MSB_BITS_POSITIVE_VE:  0x22, // READ_TDO | BIT_MODE
	IN_MSB_BITS_NEGATIVE_VE:  0x26, // READ_TDO | BIT_MODE | READ_NEGATIVE_EDGE

	IN_OUT_MSB_BYTES_OUT_NEGATIVE_IN_POSITIVE_VE: 0x31,
	IN_OUT_MSB_BYTES_OUT_POSITIVE_IN_NEGATIVE_VE: 0x34,
	IN_OUT_MSB_BITS_OUT_NEGATIVE_IN_POSITIVE_VE: 0x33,
	IN_OUT_MSB_BITS_OUT_POSITIVE_IN_NEGATIVE_VE: 0x36,

	//
	OUT_LSB_BYTES_POSITIVE_VE: 0x18, // WRITE_TDI | LSB_FIRST
	OUT_LSB_BYTES_NEGATIVE_VE: 0x19,
	OUT_LSB_BITS_POSITIVE_VE: 0x1A,
	OUT_LSB_BITS_NEGATIVE_VE: 0x1B,

	IN_LSB_BYTES_POSITIVE_VE: 0x28,
	IN_LSB_BYTES_NEGATIVE_VE: 0x2C,
	IN_LSB_BITS_POSITIVE_VE: 0x2A,
	IN_LSB_BITS_NEGATIVE_VE: 0x2E,

	IN_OUT_LSB_BYTES_OUT_NEGATIVE_IN_POSITIVE_VE: 0x39,
	IN_OUT_LSB_BYTES_OUT_POSITIVE_IN_NEGATIVE_VE: 0x3C,
	IN_OUT_LSB_BITS_OUT_NEGATIVE_IN_POSITIVE_VE: 0x3B,
	IN_OUT_LSB_BITS_OUT_POSITIVE_IN_NEGATIVE_VE: 0x3E,

}

export type ShiftCommand = number



// export const LSB_FIRST_TMS_COMMANDS = {
// 	CLOCK_DATA_NO_READ_POSITIVE_VE: 0x4A,
// 	CLOCK_DATA_NO_READ_NEGATIVE_VE: 0x4B,

// 	CLOCK_DATA_WITH_READ_ON_POSITIVE_VE_READ_POSITIVE_VE: 0x6A,
// 	CLOCK_DATA_WITH_READ_ON_NEGATIVE_VE_READ_POSITIVE_VE: 0x6B,
// 	CLOCK_DATA_WITH_READ_ON_POSITIVE_VE_READ_NEGATIVE_VE: 0x6E,
// 	CLOCK_DATA_WITH_READ_ON_NEGATIVE_VE_READ_NEGATIVE_VE: 0x6F
// }

export const PIN_STATE_COMMANDS = {
	SET_DATA_BITS_LOW_BYTE: 0x80,
	SET_DATA_BITS_HIGH_BYTE: 0x82,

	READ_DATA_BITS_LOW_BYTE: 0x81,
	READ_DATA_BITS_HIGH_BYTE: 0x83
}

// export const LOOPBACK_COMMANDS = {
// 	ENABLED: 0x84,
// 	DISABLE: 0x85
// }

export const CLOCK_DIVISOR_COMMANDS = {
	SET_CLK_DIVISOR: 0x86
}

// export const HOST_EMULATION_MODE_COMMANDS = {
// 	READ_SHORT_ADDRESS: 0x90,
// 	READ_EXTENDED_ADDRESS: 0x91,
// 	WRITE_SHORT_ADDRESS: 0x92,
// 	WRITE_EXTENDED_ADDRESS: 0x93
// }

export const HOST_AND_MPSSE_MODE_COMMANDS = {
	SEND_IMMEDIATE: 0x87,
	WAIT_IO_HIGH: 0x88,
	WAIT_IO_LOW: 0x89
}

export const H_COMMANDS = {
	DISABLE_CLOCK_DIVIDE_BY_FIVE: 0x8A,
	ENABLE_CLOCK_DIVIDE_BY_FIVE: 0x8B,

	ENABLE_THREE_PHASE_CLOCKING: 0x8C,
	DISABLE_THREE_PHASE_CLOCKING: 0x8D,

	CLOCK_N_BITS_NO_TRANSFER: 0x8E,
	CLOCK_N_EIGHT_BITS_NO_TRANSFER: 0x8F,

	CLOCK_WAIT_IO_HIGH: 0x94,
	CLOCK_WAIT_IO_LOW: 0x95,

	ENABLE_ADAPTIVE_CLOCKING: 0x96,
	DISABLE_ADAPTIVE_CLOCKING: 0x97,

	CLOCK_N_BITS_NO_TRANSFER_OR_UNTIL_HIGH: 0x9C,
	CLOCK_N_EIGHT_BITS_NO_TRANSFER_OR_UNTIL_LOW: 0x9D
}

export const FT232H_ONLY_COMMANDS = {
	SET_IO_ONLY_DRIVE_LOW: 0x9E
}
